Need to have full read permissions otherwise the agent will not run correctly:
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError:
malformed format string - %S at /etc/puppet/manifests/site.pp:18 on node
testhost.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run